version: '2'
services:
  epracas_frontend:
    volumes:
     - ./:/source
    container_name: epracas_frontend 
    build: .
    ports:
      - "4000:4000"
      - "4001:4001"
    command: bash -c "yarn install --no-optional && gulp"


